### ISSUE TITLE
add dependencies / requirement

### ISSUE THREAD

**Issue by KazeroG** [benji7425/discord-bot-rss-feed#3]
add wich dependence to have in readme

`npm WARN lifecycle discord-bot-rss-feed@3.5.2~postinstall: cannot run in wd discord-bot-rss-feed@3.5.2 cd ./core && npm install (wd=/var/www/html/dbot)`
`npm WARN discord.js@11.2.0 requires a peer of bufferutil@^3.0.2 but none is installed. You must install peer dependencies yourself.`
`npm WARN discord.js@11.2.0 requires a peer of erlpack@hammerandchisel/erlpack but none is installed. You must install peer dependencies yourself.`
`npm WARN discord.js@11.2.0 requires a peer of node-opus@^0.2.6 but none is installed. You must install peer dependencies yourself.`
`npm WARN discord.js@11.2.0 requires a peer of opusscript@^0.0.3 but none is installed. You must install peer dependencies yourself.`
`npm WARN discord.js@11.2.0 requires a peer of sodium@^2.0.1 but none is installed. You must install peer dependencies yourself.`
`npm WARN discord.js@11.2.0 requires a peer of libsodium-wrappers@^0.5.4 but none is installed. You must install peer dependencies yourself.`
`npm WARN discord.js@11.2.0 requires a peer of uws@^0.14.5 but none is installed. You must install peer dependencies yourself.`

**Comment by benji7425** [comment]
These errors are a red herring, those dependencies are only needed if the bot uses voice, which this one doesn't.
