### ISSUE TITLE
RSS excerpt

### ISSUE THREAD

**Issue by Oreolek** [benji7425/discord-bot-rss-feed#4]
> Article content too long for a single Discord message!

You can post an excerpt then.

**Comment by benji7425** [comment]
Probably going to do this in future

**Comment by Oreolek** [comment]
added [here](https://source.heropunch.io/oreolek/discord-bot-rss-feed)

**Comment by benji7425** [comment]
#6 should solve this, when I relaunch the bots I'll make sure this is included.
